// Shared File:-path picker — one implementation driving both the mobile
// description-editor modal (modals.js) and the desktop in-row description panel
// (#descSibling, built in toDoRow.js).
//
// The picker is a ⌖ target chip that lists the active project's source files
// (read SYNCHRONOUSLY from the manifest structureView already fetched and
// cached) and, on selection, writes the chosen path into the entry's `File:`
// line — removing the one authoring step that depended on holding repo paths in
// your head. When the active project has no linked repo, or that repo's manifest
// was never loaded (CI hasn't published it, or Structure was never opened this
// session), the chip stays hidden entirely rather than opening an empty picker
// or blocking on a fetch.
//
// This module owns the search filter, the row cap, the `File:`-line insertion
// logic, and the manifest read. The two hosts differ only in where the chip and
// panel mount and what side effects run after a pick (persist + refresh), passed
// in via options — so the two surfaces can never diverge.

import { listLogic } from './listLogic.js';
import { findTargetById } from './inject.js';
// structureView.js owns the async load-and-cache; here we only read what it
// already cached — no re-fetch, no network call on the render path.
import { getCachedManifest } from './claudeSheet.js';

// Cap the rendered rows so a several-hundred-file manifest never mounts in full
// (on a phone, or in the desktop panel); when the filter still matches more than
// the cap, show a "keep typing to narrow" hint instead of the overflow.
const TARGET_PICK_CAP = 60;

// Split a `File:` line value on commas and report whether `path` is already one
// of its comma-separated tokens once backticks and surrounding whitespace are
// stripped. Used to make re-selecting an already-listed path a no-op.
function filePathPresent(fileValue, path) {
    return String(fileValue || '').split(',').some(function (token) {
        return token.replace(/`/g, '').trim() === path;
    });
}

// Detect the indentation used by the entry's sub-bullets so a freshly-inserted
// `- File:` line matches them. Entries arrive from several sources (hand-typed,
// pasted from chat, generated by triage) with two-space-indented sub-bullets by
// convention; fall back to two spaces when no indented bullet is found.
function detectSubBulletIndent(lines) {
    for (let i = 0; i < lines.length; i++) {
        const m = lines[i].match(/^(\s+)-\s/);
        if (m) return m[1];
    }
    return '  ';
}

// Insert a repo-relative source `path` into a TODO.md-style entry's `File:`
// line, backtick-wrapped, and return the updated entry text. If a `- File:`
// line already exists (matched tolerantly of leading whitespace and case), the
// path is appended to it comma-separated — unless it is already listed, in
// which case the text is returned unchanged (no duplicate). If there is no
// `File:` line, a new one is inserted immediately before the `- Completed:`
// line (matching its indent), or at the end of the entry when no Completed line
// is present. The body is never reformatted — only the one line changes.
export function insertFilePathIntoEntry(text, path) {
    const raw = String(path || '').trim();
    const source = String(text || '');
    if (!raw) return source;
    const wrapped = '`' + raw + '`';
    const lines = source.split('\n');

    // Tolerant File: matcher — leading whitespace, `- File:`, case-insensitive.
    const fileLineRe = /^(\s*)-\s*File:\s*(.*)$/i;
    for (let i = 0; i < lines.length; i++) {
        const m = lines[i].match(fileLineRe);
        if (!m) continue;
        if (filePathPresent(m[2], raw)) return source;
        const trimmedEnd = lines[i].replace(/\s+$/, '');
        // An empty `File:` line (no value yet) takes the path directly; an
        // existing value gets it appended comma-separated.
        lines[i] = /:\s*$/.test(trimmedEnd)
            ? trimmedEnd + ' ' + wrapped
            : trimmedEnd + ', ' + wrapped;
        return lines.join('\n');
    }

    // No File: line — insert one immediately before `- Completed:` if present.
    const completedRe = /^(\s*)-\s*Completed:/i;
    for (let i = 0; i < lines.length; i++) {
        const m = lines[i].match(completedRe);
        if (!m) continue;
        lines.splice(i, 0, (m[1] || '') + '- File: ' + wrapped);
        return lines.join('\n');
    }

    // No Completed line — append inside the block, past any trailing blank lines,
    // matching the sibling sub-bullets' indent.
    const indent = detectSubBulletIndent(lines);
    let end = lines.length;
    while (end > 0 && lines[end - 1].trim() === '') end--;
    lines.splice(end, 0, indent + '- File: ' + wrapped);
    return lines.join('\n');
}

// Resolve a project's linked repo (the same getProjectTargetId → findTargetById
// path the inject button uses) so the picker can read that repo's cached
// manifest. Returns null when the project has no routing target, in which case
// the picker stays hidden.
function resolveProjectRepo(projectName) {
    if (!projectName) return null;
    const targetId = listLogic.getProjectTargetId(projectName);
    if (!targetId) return null;
    const target = findTargetById(targetId);
    return target && target.repo ? target.repo : null;
}

// Read the active project's manifest file list synchronously from the cache.
// Returns [] when there is no linked repo or the manifest was never loaded —
// the caller hides the picker in that case.
export function resolveManifestFilesForProject(projectName) {
    const repo = resolveProjectRepo(projectName || '');
    const cached = getCachedManifest(repo);
    return (cached && cached.ok && Array.isArray(cached.files)) ? cached.files : [];
}

// Build the shared File:-path picker (trigger chip + searchable panel) and wire
// it, returning the two mount points plus an `available` flag so the host can
// decide placement. The trigger self-hides when the project has no manifest.
//
// Options:
//   projectName  — the active project, for the manifest read.
//   textarea     — the entry textarea the pick is written into (required).
//   onInsert     — host side effects after a pick lands in the textarea
//                  (persist, refresh inject button, recompute layout). The
//                  picker has already set textarea.value and dispatched `input`.
//   triggerId    — optional id for the trigger element (kept for the modal's
//                  existing hooks; the shared class carries all styling).
//   panelId      — optional id for the panel element.
export function createFilePicker(options) {
    const opts = options || {};
    const projectName = opts.projectName || '';
    const textarea = opts.textarea;
    const onInsert = typeof opts.onInsert === 'function' ? opts.onInsert : function () {};
    const manifestFiles = resolveManifestFilesForProject(projectName);

    const trigger = document.createElement('button');
    trigger.className = 'filePickTrigger';
    trigger.type = 'button';
    trigger.textContent = '⌖';
    trigger.setAttribute('aria-label', 'Pick a file path from the project');
    trigger.setAttribute('aria-expanded', 'false');
    if (opts.triggerId) trigger.id = opts.triggerId;
    // Hidden entirely when there is no manifest to browse.
    if (!manifestFiles.length) trigger.style.display = 'none';

    const panel = document.createElement('div');
    panel.className = 'filePickPanel';
    panel.hidden = true;
    if (opts.panelId) panel.id = opts.panelId;

    const search = document.createElement('input');
    search.className = 'filePickSearch';
    search.type = 'text';
    search.setAttribute('aria-label', 'Filter files');
    search.placeholder = 'Filter files…';
    search.autocomplete = 'off';
    search.spellcheck = false;

    const list = document.createElement('div');
    list.className = 'filePickList';
    list.setAttribute('role', 'listbox');

    panel.appendChild(search);
    panel.appendChild(list);

    function applyFilePick(path) {
        if (!textarea) return;
        textarea.value = insertFilePathIntoEntry(textarea.value, path);
        // Route the change through the textarea's own input listener (auto-grow,
        // and on the modal the item.desc + inject-button re-sync), then let the
        // host persist + refresh through its own listLogic path.
        textarea.dispatchEvent(new Event('input'));
        onInsert();
        closePanel();
    }

    function renderList() {
        const q = (search.value || '').trim().toLowerCase();
        const matches = q
            ? manifestFiles.filter(function (p) { return p.toLowerCase().indexOf(q) !== -1; })
            : manifestFiles;
        list.innerHTML = '';
        if (!matches.length) {
            const empty = document.createElement('p');
            empty.className = 'filePickEmpty';
            empty.textContent = 'No files match';
            list.appendChild(empty);
            return;
        }
        matches.slice(0, TARGET_PICK_CAP).forEach(function (path) {
            const row = document.createElement('button');
            row.type = 'button';
            row.className = 'filePickRow';
            row.setAttribute('role', 'option');
            row.textContent = path;
            row.addEventListener('click', function () { applyFilePick(path); });
            list.appendChild(row);
        });
        if (matches.length > TARGET_PICK_CAP) {
            const more = document.createElement('p');
            more.className = 'filePickEmpty';
            more.textContent = 'Keep typing to narrow ' + matches.length + ' matches';
            list.appendChild(more);
        }
    }

    function openPanel() {
        panel.hidden = false;
        trigger.setAttribute('aria-expanded', 'true');
        renderList();
        try { search.focus(); } catch (e) { /* defensive */ }
    }
    function closePanel() {
        panel.hidden = true;
        trigger.setAttribute('aria-expanded', 'false');
    }

    trigger.addEventListener('click', function () {
        if (panel.hidden) openPanel();
        else closePanel();
    });
    search.addEventListener('input', renderList);

    return { trigger, panel, available: manifestFiles.length > 0 };
}
